Compilar soluciones

diff --git a/.github/workflows/build.yaml b/.github/workflows/build.yaml
--- a/.github/workflows/build.yaml
+++ b/.github/workflows/build.yaml
@@ -21,13 +21,37 @@ jobs:
       
       - uses: typst-community/setup-typst@v4
 
-      - name: Compile Typst examples to PDF
+      - name: Compile Typst examples with solution to PDF
         shell: bash
         run: |
           find ./Material -type f -name "*.typ" | while read -r archivo; do
               echo "Compilando: $archivo"
               typst compile "$archivo" --root . --input show-solutions=true || echo "Error en $archivo, continuando..."
           done
+
+      - name: Rename files to (solution)
+        shell: bash
+        run: |
+          find . -type f -iname '*.pdf' -print0 | while IFS= read -r -d '' f; do
+            dir=$(dirname "$f")
+            base=$(basename "$f" .pdf)
+
+            # Evitar renombrar si ya termina en (soluciones)
+            if [[ "$base" == *"(soluciones)" ]]; then
+                continue
+            fi
+
+            mv "$f" "$dir/$base (soluciones).pdf"
+          done
+
+      - name: Compile Typst examples without solution to PDF
+        shell: bash
+        run: |
+          find ./Material -type f -name "*.typ" | while read -r archivo; do
+              echo "Compilando: $archivo"
+              typst compile "$archivo" --root . --input show-solutions=false || echo "Error en $archivo, continuando..."
+          done
+
 
       - name: Upload PDF file
         uses: actions/upload-artifact@v4
