Compilar apuntes como html y pdf

diff --git a/.github/workflows/build-Ejercicios.yaml b/.github/workflows/build-Ejercicios.yaml
--- a/.github/workflows/build-Ejercicios.yaml
+++ b/.github/workflows/build-Ejercicios.yaml
@@ -77,6 +77,7 @@ jobs:
           find ./Material -type f -name "Apuntes-*.typ" | while read -r archivo; do
               echo "Compilando: $archivo"
               typst compile "$archivo" --root . --input show-solutions=false || echo "Error en $archivo, continuando..."
+              typst compile "$archivo" --format html --features html --root . --input show-solutions=false || echo "Error en $archivo, continuando..."
           done
       
       - name: Compile Typst Apuntes to html
